clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      remote: http://gitea:3000/${CI_REPO}.git
      branch: main

x-skip-ci: &skip_ci |
  case "${CI_COMMIT_MESSAGE:-}" in
    *update\ woodpecker\ filter*|*sync\ workspace\ into\ Gitea*)
      echo "Skipping pipeline for internal sync commit"
      exit 0
      ;;
  esac

steps:
  test:
    image: python:3.10-slim
    commands:
      - *skip_ci
      - cd hello-api
      - pip install -r requirements.txt pytest
      - pytest -q

  train-model:
    image: python:3.10-slim
    environment:
      MLFLOW_TRACKING_URI: http://10.89.0.1:30902
      MLFLOW_EXPERIMENT_NAME: hello-api-training
    commands:
      - *skip_ci
      - mkdir -p ml/artifacts
      - pip install -r ml/requirements.txt
      - MODEL_OBJECT="ml-models/iris-${CI_COMMIT_SHA}.joblib"; python ml/train.py --output ml/artifacts/model.joblib --commit "${CI_COMMIT_SHA}" --model-object "$MODEL_OBJECT" --model-sha-path ml/artifacts/model.sha; echo "$MODEL_OBJECT" > ml/artifacts/model.object

  upload-model:
    image: minio/mc:latest
    environment:
      MINIO_ENDPOINT: http://10.89.0.1:9090
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    commands:
      - *skip_ci
      - MODEL_OBJECT=$(cat ml/artifacts/model.object)
      - mc alias set minio "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
      - mc mb --ignore-existing minio/ml-models
      - mc cp ml/artifacts/model.joblib "minio/$MODEL_OBJECT"
      - mc stat "minio/$MODEL_OBJECT"

  build:
    image: docker:24.0-cli
    environment:
      DOCKER_HOST: tcp://10.89.0.1:2375
    commands:
      - *skip_ci
      - docker build -t registry.localhost:5002/hello-api:${CI_COMMIT_SHA} -f hello-api/Dockerfile hello-api
      - docker push registry.localhost:5002/hello-api:${CI_COMMIT_SHA}
    when:
      status: [success]

  scan:
    image: aquasec/trivy:0.50.2
    environment:
      TRIVY_INSECURE: "true"
      TRIVY_SKIP_DB_UPDATE: "true"
    commands:
      - *skip_ci
      - trivy image --exit-code 0 --severity HIGH,CRITICAL --scanners vuln --insecure 10.89.0.1:5002/hello-api:${CI_COMMIT_SHA} || echo "trivy skipped (offline)"
    when:
      status: [success]

  update-gitops:
    image: alpine/git
    environment:
      GITEA_USER:
        from_secret: gitea_user
      GITEA_TOKEN:
        from_secret: gitea_token
    commands:
      - *skip_ci
      - git config --global user.email "ci@gitopslab.local"
      - git config --global user.name "woodpecker"
      - cd gitops/apps/hello
      - 'sed -i "s#^[[:space:]]*image:.*#          image: registry.localhost:5002/hello-api:${CI_COMMIT_SHA}#" deployment.yaml'
      - 'MODEL_OBJECT=$(cat ../../../ml/artifacts/model.object); MODEL_SHA=$(cat ../../../ml/artifacts/model.sha); sed -i "s#MODEL_OBJECT:.*#MODEL_OBJECT: $MODEL_OBJECT#" model-configmap.yaml; sed -i "s#MODEL_SHA:.*#MODEL_SHA: $MODEL_SHA#" model-configmap.yaml'
      - git add deployment.yaml model-configmap.yaml
      - 'git commit -m "chore: bump hello-api image to ${CI_COMMIT_SHA} [skip ci]" || echo "no changes"'
      - 'git remote set-url origin "http://${GITEA_USER}:${GITEA_TOKEN}@gitea:3000/${CI_REPO}.git"'
      - 'git push origin HEAD:main'
    when:
      status: [success]
      event: [push]

when:
  event: [push, manual]
  message:
    exclude:
      - '^chore\(e2e\):'
      - '^chore: sync workspace into Gitea'
