apiVersion: batch/v1
kind: Job
metadata:
  name: minio-seed-model
  labels:
    app: minio
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ROOT_PASSWORD
          command:
            - sh
            - -c
            - |
              set -e
              echo "[seed] waiting for minio..."
              until mc alias set minio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "[seed] minio not ready, retrying..."
                sleep 2
              done
              mc mb --ignore-existing minio/ml-models
              mc cp /seed/iris.joblib minio/ml-models/iris.joblib
              mc stat minio/ml-models/iris.joblib
          volumeMounts:
            - name: seed
              mountPath: /seed
      volumes:
        - name: seed
          configMap:
            name: minio-seed-model
